Move around

diff --git a/home/.aws/useaws b/home/.aws/useaws
--- a/home/.aws/useaws
+++ b/home/.aws/useaws
@@ -4,27 +4,6 @@ set -o errexit
 set -o pipefail
 set -o nounset
 
-AWS_DIR=~/.aws
-AWS_CACHE_DIR=${AWS_DIR}/cli/cache
-
-# Check dependencies.
-[[ -d ${AWS_DIR} ]] || (echo "Missing ${AWS_DIR} dir" && false)
-which aws > /dev/null || (echo "Missing dependency: aws" && false)
-which jq > /dev/null || (echo "Missing dependency: jq" && false)
-
-if [[ -n "${AWS_ACCESS_KEY_ID:-}" ]]; then
-	echo "WARNING: AWS_ACCESS_KEY_ID is already set and may cause unwanted behavior"
-fi
-if [[ -n "${AWS_SECRET_ACCESS_KEY:-}" ]]; then
-	echo "WARNING: AWS_SECRET_ACCESS_KEY is already set and may cause unwanted behavior"
-fi
-if [[ -n "${AWS_SESSION_TOKEN:-}" ]]; then
-	echo "WARNING: AWS_SESSION_TOKEN is already set and may cause unwanted behavior"
-fi
-if [[ -n "${AWS_PROFILE:-}" ]]; then
-	echo "WARNING: AWS_PROFILE is already set and may cause unwanted behavior"
-fi
-
 script=$(basename "$0")
 
 function usage {
@@ -46,6 +25,27 @@ function usage {
 	echo "$ ${script} no (unsets active credentials)"
 	exit 1
 }
+
+AWS_DIR=~/.aws
+AWS_CACHE_DIR=${AWS_DIR}/cli/cache
+
+# Check dependencies.
+[[ -d ${AWS_DIR} ]] || (echo "Missing ${AWS_DIR} dir" && false)
+which aws > /dev/null || (echo "Missing dependency: aws" && false)
+which jq > /dev/null || (echo "Missing dependency: jq" && false)
+
+if [[ -n "${AWS_ACCESS_KEY_ID:-}" ]]; then
+	echo "WARNING: AWS_ACCESS_KEY_ID is already set and may cause unwanted behavior"
+fi
+if [[ -n "${AWS_SECRET_ACCESS_KEY:-}" ]]; then
+	echo "WARNING: AWS_SECRET_ACCESS_KEY is already set and may cause unwanted behavior"
+fi
+if [[ -n "${AWS_SESSION_TOKEN:-}" ]]; then
+	echo "WARNING: AWS_SESSION_TOKEN is already set and may cause unwanted behavior"
+fi
+if [[ -n "${AWS_PROFILE:-}" ]]; then
+	echo "WARNING: AWS_PROFILE is already set and may cause unwanted behavior"
+fi
 
 function write_signature {
 	# Saves to ~/.aws/config:
