Support setting from env vars in useaws

diff --git a/home/.aws/useaws b/home/.aws/useaws
--- a/home/.aws/useaws
+++ b/home/.aws/useaws
@@ -7,21 +7,22 @@ set -o nounset
 script=$(basename "$0")
 
 function usage {
-	echo "Set active AWS credentials from a user or a role."
+	echo "Set active AWS credentials from user, role or env."
 	echo
 	echo "Works seemlessly with the CLI and SDKs, since the desired credentials"
-	echo "are copied into the default in ~/.aws/credentials."
+	echo "are copied into the 'default' in ~/.aws/credentials."
 	echo
 	echo "Uses the CLI for any heavy lifting, so features like MFA etc."
 	echo "should just work."
 	echo
-	echo "IMPORTANT: Move your default credentials before using, since this"
+	echo "IMPORTANT: Move your 'default' credentials before using, since this"
 	echo "script will maintain that section. Keep your users and roles in"
 	echo "named sections."
 	echo
 	echo "Usage:"
 	echo "$ ${script} role <profile in ~/.aws/config>"
 	echo "$ ${script} user <profile in ~/.aws/credentials>"
+	echo "$ ${script} env (sets active credentials from env vars)"
 	echo "$ ${script} whoami (shows active credentials)"
 	echo "$ ${script} no (unsets active credentials)"
 	exit 1
@@ -30,32 +31,32 @@ function usage {
 AWS_DIR=~/.aws
 AWS_CACHE_DIR=${AWS_DIR}/cli/cache
 
+# Ensure files exist and have final newlines (`aws configure` messes up otherwise).
+mkdir -p "${AWS_DIR}"
+touch "${AWS_DIR}/config"
+touch "${AWS_DIR}/credentials"
+[[ -n $(tail -c1 "${AWS_DIR}/config") ]] && echo >> "${AWS_DIR}/config"
+[[ -n $(tail -c1 "${AWS_DIR}/credentials") ]] && echo >> "${AWS_DIR}/credentials"
+
 # Check dependencies.
-[[ -d ${AWS_DIR} ]] || (echo "Missing ${AWS_DIR} dir" && false)
 which aws > /dev/null || (echo "Missing dependency: aws" && false)
 which jq > /dev/null || (echo "Missing dependency: jq" && false)
-
-if [[ "${AWS_ACCESS_KEY_ID:-}" != "" ]]; then
-	echo "WARNING: AWS_ACCESS_KEY_ID is already set and may cause unwanted behavior"
-fi
-if [[ "${AWS_SECRET_ACCESS_KEY:-}" != "" ]]; then
-	echo "WARNING: AWS_SECRET_ACCESS_KEY is already set and may cause unwanted behavior"
-fi
-if [[ "${AWS_SESSION_TOKEN:-}" != "" ]]; then
-	echo "WARNING: AWS_SESSION_TOKEN is already set and may cause unwanted behavior"
-fi
-if [[ "${AWS_PROFILE:-}" != "" ]]; then
-	echo "WARNING: AWS_PROFILE is already set and may cause unwanted behavior"
-fi
 
 function write_signature {
 	# Saves to ~/.aws/config:
 	aws configure set default.managed_by "${script}"
 }
 
-# Ensure final newlines in files (`aws configure` messes up otherwise).
-[[ -n $(tail -c1 "${AWS_DIR}/config") ]] && echo '' >> "${AWS_DIR}/config"
-[[ -n $(tail -c1 "${AWS_DIR}/credentials") ]] && echo '' >> "${AWS_DIR}/credentials"
+function set_default_credentials {
+	access_key_id=$1
+	secret_access_key=$2
+	session_token=$3
+
+	# Saves to ~/.aws/credentials:
+	aws configure set default.aws_access_key_id "${access_key_id}"
+	aws configure set default.aws_secret_access_key "${secret_access_key}"
+	aws configure set default.aws_session_token "${session_token}"
+}
 
 action=${1:-}
 
@@ -63,11 +64,46 @@ if [[ "${action}" == "" ]]; then
 	usage
 fi
 
+if [[ "${action}" == "env" ]]; then
+	# Grab the desired credentials.
+	access_key_id="${AWS_ACCESS_KEY_ID:-}"
+	if [[ "${access_key_id}" == "" ]]; then
+		echo "!!! AWS_ACCESS_KEY_ID must be set in env"
+		exit 1
+	fi
+	secret_access_key="${AWS_SECRET_ACCESS_KEY:-}"
+	if [[ "${secret_access_key}" == "" ]]; then
+		echo "!!! AWS_SECRET_ACCESS_KEY must be set in env"
+		exit 1
+	fi
+	session_token="${AWS_SESSION_TOKEN:-}"
+
+	set_default_credentials "${access_key_id}" "${secret_access_key}" "${session_token}"
+
+	write_signature
+
+	echo "Set default credentials from env vars (with ID: ${access_key_id})"
+	echo
+	echo "NOTE: You no longer need the AWS_* variables in your shell, so feel"
+	echo "to unset them or exit this shell."
+	exit 0
+fi
+
+if [[ "${AWS_ACCESS_KEY_ID:-}" != "" ]]; then
+	echo "WARNING: AWS_ACCESS_KEY_ID exists in env and may cause unwanted behavior"
+fi
+if [[ "${AWS_SECRET_ACCESS_KEY:-}" != "" ]]; then
+	echo "WARNING: AWS_SECRET_ACCESS_KEY exists in env and may cause unwanted behavior"
+fi
+if [[ "${AWS_SESSION_TOKEN:-}" != "" ]]; then
+	echo "WARNING: AWS_SESSION_TOKEN exists in env and may cause unwanted behavior"
+fi
+if [[ "${AWS_PROFILE:-}" != "" ]]; then
+	echo "WARNING: AWS_PROFILE exists in env and may cause unwanted behavior"
+fi
+
 if [[ "${action}" == "no" ]]; then
-	# Saves to ~/.aws/credentials:
-	aws configure set default.aws_access_key_id ""
-	aws configure set default.aws_secret_access_key ""
-	aws configure set default.aws_session_token ""
+	set_default_credentials "" "" ""
 
 	write_signature
 
@@ -101,14 +137,19 @@ fi
 
 if [[ "${action}" == "user" ]]; then
 	# Grab the desired credentials.
-	access_key_id=$(aws configure get ${profile}.aws_access_key_id)
+	access_key_id=$(aws configure get ${profile}.aws_access_key_id || echo)
+	if [[ "${access_key_id}" == "" ]]; then
+		echo "!!! Could not find access_key_id for user: ${profile}"
+		exit 1
+	fi
 	secret_access_key=$(aws configure get ${profile}.aws_secret_access_key)
+	if [[ "${secret_access_key}" == "" ]]; then
+		echo "!!! Could not find secret_access_key for user: ${profile}"
+		exit 1
+	fi
 	session_token=$(aws configure get ${profile}.aws_session_token || echo)
 
-	# Saves to ~/.aws/credentials:
-	aws configure set default.aws_access_key_id "${access_key_id}"
-	aws configure set default.aws_secret_access_key "${secret_access_key}"
-	aws configure set default.aws_session_token "${session_token}"
+	set_default_credentials "${access_key_id}" "${secret_access_key}" "${session_token}"
 
 	write_signature
 
@@ -142,10 +183,7 @@ if [[ "${action}" == "role" ]]; then
 	secret_access_key=$(echo $creds | jq --raw-output '.SecretAccessKey')
 	session_token=$(echo $creds | jq --raw-output '.SessionToken')
 
-	# Saves to ~/.aws/credentials:
-	aws configure set default.aws_access_key_id "${access_key_id}"
-	aws configure set default.aws_secret_access_key "${secret_access_key}"
-	aws configure set default.aws_session_token "${session_token}"
+	set_default_credentials "${access_key_id}" "${secret_access_key}" "${session_token}"
 
 	write_signature
 
